### ISSUE TITLE
Change AT_ASSERT to AT_CHECK

### ISSUE THREAD

**Issue by ClementPinard** [pytorch/extension-cpp#11]
This is an issue regarding pytorch master and not 0.4.0 , so I don't put it directly in a PR, but might be good to know this

[This line](https://github.com/pytorch/extension-cpp/blob/master/cuda/lltm_cuda.cpp#L27) (and the next) make the compilation fail when using master build (and nightly builds I believe) because the function definition has changed.

Now there's apparently a lot of refactoring going on in pytorch right now so it may change again in the future but the correct way to call this line is now

```cpp
#define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDA tensor")
#define CHECK_CONTIGUOUS(x) AT_CHECK(x.is_contiguous(), #x, " must be contiguous")
```

see [this commit](https://github.com/pytorch/pytorch/commit/0427afadd1a2a9b0c12906664d010920b6f8c6fb#diff-5bac3cb350a8b65d85da919af9bc6f44R128) for explanation.

**Comment by goldsborough** [comment]
Yes, that's correct. I will add a comment for now, and update with the next release
