### ISSUE TITLE
Custom C++ extension : torch/torch.h not found

### ISSUE THREAD

**Issue by adarsh-kr** [pytorch/extension-cpp#22]
I am following [this tutorial](https://pytorch.org/tutorials/advanced/cpp_extension.html) to create a C++ extension for Pytorch. My C++ code is giving following error :

```
test.cpp:3:10: fatal error: torch/torch.h: No such file or directory
 #include <torch/torch.h>


```
How to get torch.h header file ? Is there some ```pytorch-dev``` version ?

**Comment by goldsborough** [comment]
Hi, please provide more information about your environment. What version of PyTorch are you using?

**Comment by adarsh-kr** [comment]
I am using torch==0.4.1.

**Comment by goldsborough** [comment]
What commands did you run to arrive at this compiler error? Please provide as much context as possible for me to help.

**Comment by adarsh-kr** [comment]
@goldsborough I have added all the info in the above comment. Please let me know if you have any questions.

**Comment by goldsborough** [comment]
You are not supposed to compile this code manually like this. Have you seen the setup.py and torch.utils.cpp_extensions.load instructions in the tutorial? I think it is explained quite well how to build an extension using the means we provide.

**Comment by adarsh-kr** [comment]
Can u pls tell me how build this ?

**Comment by goldsborough** [comment]
It is explained in the tutorial here: https://pytorch.org/tutorials/advanced/cpp_extension.html#building-with-setuptools
