### ISSUE TITLE
CUDA_HOME environment variable is not set

### ISSUE THREAD

**Issue by zzd1992** [pytorch/extension-cpp#26]
I work on ubuntu16.04, cuda9.0 and Pytorch1.0.
When I run your example code `cuda/setup.py`:
```
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    'lltm_cuda_kernel.cu',
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/cpp_extension.py", line 476, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/cpp_extension.py", line 549, in library_paths
    paths.append(_join_cuda_home(lib_dir))
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/cpp_extension.py", line 1121, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
EnvironmentError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```
However, I am sure cuda9.0 in my computer is installed correctly.
How to fix this problem?

**Comment by goldsborough** [comment]
That's odd. Maybe you have an unusual install location for CUDA. Either way, just setting `CUDA_HOME` to your cuda install path before running `python setup.py` should work: `CUDA_HOME=/path/to/your/cuda/home python setup.py install`

**Comment by zzd1992** [comment]
Thanks. My problem is solved.

**Comment by zzd1992** [comment]
Sorry, I meet another problem when I run `python jit.py` (my python version is 2.7.12).
```
Using /tmp/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/lltm_cuda/build.ninja...
Building extension module lltm_cuda...
Traceback (most recent call last):
  File "jit.py", line 3, in <module>
    'lltm_cuda', ['lltm_cuda.cpp', 'lltm_cuda_kernel.cu'], verbose=True)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/cpp_extension.py", line 863, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/cpp_extension.py", line 958, in _build_extension_module
    message += ": {}".format(error.output.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 1721: ordinal not in range(128)
```
It looks a coding problem of python2.7.
I skip this step and directly run the benchmark code with batchsize=128. I get the following results:
```
python benchmark.py py
Forward: 545.025/731.578 us | Backward 735.044/875.993 us

python benchmark.py cuda
Forward: 93.937/101.736 us | Backward 273.943/345.180 us
```
Is it reasonable?
How much the speed can be further improved if compiled with jit?

**Comment by DaLei001** [comment]
@zzd1992 Could you tell how to solve the problem about "the CUDA_HOME environment variable is not set"?

**Comment by zzd1992** [comment]
> @zzd1992 Could you tell how to solve the problem about "the CUDA_HOME environment variable is not set"?
```
CUDA_HOME=/path/to/your/cuda/home python setup.py install
```

**Comment by zzd1992** [comment]
@DaLei001 
```
CUDA_HOME=/path/to/your/cuda/home python setup.py install
```
This is worked in my situation.

**Comment by mmahdavian** [comment]
I am getting this error in a conda env on a server and I have cudatoolkit installed on the conda env. What should the CUDA_HOME be in my case.

**Comment by parasdegregore** [comment]
@mmahdavian cudatoolkit probably won't work for you, it doesn't provide access to low level c++ apis. You'd need to install CUDA using the official method.

**Comment by ShoufaChen** [comment]
I got a similar error when using pycharm, with unusual cuda install location.

I just add the `CUDA_HOME` env and solve this problem.

**Comment by fengyuan1993012** [comment]
The problem could be solved by installing the whole cuda through the nvida website. and when installing it, you may come across some problem. then https://askubuntu.com/questions/1280205/problem-while-installing-cuda-toolkit-in-ubuntu-18-04/1315116#1315116?newreg=ec85792ef03b446297a665e21fff5735  the answer may be to help you. GOOD LUCK

**Comment by saadam1n** [comment]
I am getting this issue on Windows. The weird thing is, I have set CUDA_HOME and when I run the code from pytorch to find CUDA_HOME outside of the pip installer, it works perfectly. Does pip hide environment variables?

**Comment by saadam1n** [comment]
Upon further debugging, it seems that install of torch that pip installs in its isolated build environment cannot detect CUDA. However, the install of torch outside it can. Unfortunately, building with `--no-build-isolation` leads to a ton of other errors.

**Comment by tom-papatheodore** [comment]
Hello. I recently ran into this issue as well because my CUDA install was in a non-default location since I have multiple installs (not uncommon on large shared systems either). Google brought me here, which showed how to resolve the issue with `CUDA_HOME`. 

Might I suggest simply adding in a `NOTE` or something in the README that describes the `CUDA_HOME` environment variable? I'd submit a PR myself, but I thought I'd instead ask one of the devs of this project to add it since that's much simpler than having to sign a contributor license agreement (since it's just a one-liner).

Thanks for your consideration :)
