### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by andrei-pokrovsky** [pytorch/extension-cpp#3]
Looks like the link in the README to
http://pytorch.org/docs/master/notes/cpp-extensions.html

Is broken.

**Comment by goldsborough** [comment]
Yeah, we're waiting for the next release to publish the tutorial. I'll keep this issue open until then.

**Comment by t-vi** [comment]
I like your tutorial so much, maybe one could include a temporary link here:
https://github.com/goldsborough/tutorials/blob/6e4a693f4ad056ac837b44db839822e29a8be3a1/advanced_source/cpp_extension.rst

**Comment by goldsborough** [comment]
Good idea, I've updated the README.
