### ISSUE TITLE
[feature request] use torch namespace instead of at

### ISSUE THREAD

**Issue by ClementPinard** [pytorch/extension-cpp#31]
A suggested by the title, should we use the `torch::` instead of `at::` in the cpp and cuda modules ?

It's suggested [here](https://github.com/pytorch/pytorch/blob/master/docs/cpp/source/notes/faq.rst#i-created-a-tensor-using-a-function-from-at-and-get-errors), so maybe this could be updated ?

I can do a PR, just checking if there's a reason not to do it

**Comment by soumith** [comment]
checking with @gchanan and @yf225 , is this fine to do?

**Comment by yf225** [comment]
Yes we should use `torch::` in the cpp and cuda modules as we are deprecating the `at::` namespace in the public API. @ClementPinard We would love to have PR contribution on it. Thanks!

**Comment by gchanan** [comment]
which cpu and cuda modules are you talking about?

**Comment by ClementPinard** [comment]
https://github.com/pytorch/extension-cpp/tree/master/cpp
https://github.com/pytorch/extension-cpp/tree/master/cuda

Also, I would like to make this example more up to date in general to help people develop cuda modules easily.
More specificly, I'd like to solve the `fmax` issue that seems to bother many people since the beginning, and seems to be solvable by a `scalar_t` cast. (see #27 , this does not seem to be an environment error).

Besides, as suggested #12 , I'd like to add usage of `.packed_accessor` in the cuda kernel.

Finally, I'd like to update the tutorial code [here](https://github.com/pytorch/tutorials/blob/master/advanced_source/cpp_extension.rst) to reflect those changes, along maybe a mention to `packed_accessor` in the tensor basics doc [here](https://github.com/pytorch/pytorch/blob/master/docs/cpp/source/notes/tensor_basics.rst)

How does that sound to you ? Unfortunately, i'm stuck at the moment because of #27 but hopefully I'll find a solution or a working setup where the code compiles.
