### ISSUE TITLE
how to debug cuda code

### ISSUE THREAD

**Issue by AceCoooool** [pytorch/extension-cpp#4]
hi, @goldsborough , Is there a good way to debug `.cu` code ? 
From your great tutorial, I write a extension of [ROI Align&ROI Pool](https://github.com/AceCoooool/RoIAlign-RoIPool-pytorch). The cpp code is pretty easy to debug (just as the pure c++ code), however, i find it "troublesome" to debug of the `cuda` code (run `python setup.py install` again and again), and nvcc will raise error about cannot find ATen library. 

Would you have any advice for debug cuda code?

Thank you ! 
(I find there are little discussions about c++ extension in Forums, so i pull an issue here. )

**Comment by goldsborough** [comment]
Hi, can you post the error you received here? Maybe I can help. Can you also fill out the [issue template](https://github.com/pytorch/extension-cpp/blob/master/.github/ISSUE_TEMPLATE.md) you were presented with? Thanks!

**Comment by AceCoooool** [comment]
Thanks for response, I did not find error yet. ~ I just curious about how to debug cuda code efficiently (Maybe it's inappropriate to discuss this topic here). I will close this issue. However, if anyone have good advice, can share it~ :smile:

**Comment by Txusheng** [comment]
> Thanks for response, I did not find error yet. ~ I just curious about how to debug cuda code efficiently (Maybe it's inappropriate to discuss this topic here). I will close this issue. However, if anyone have good advice, can share it~ 😄

Hi, do you find an efficient way to debug cuda code now?
