### ISSUE TITLE
python grad_check.py cuda Error google colab

### ISSUE THREAD

**Issue by mr-yamraj** [pytorch/extension-cpp#42]
I am running it on google colab and python grad_check.py cuda is not passing successfully, others (py, cpp) are passing with no issues.

**Comment by ClementPinard** [comment]
This is a known issue, related with the fact that fminf and fmaxf are casting to float32 and thus the grad_check will fail.

See end of issue #27 for a discussion about it.

Bottom line is you should not care about this test, as the float32 precision si enough most of the time. If you really need to have float64 precision, be it to pas the grad_check or anything else, you will need to change the code in The cuda/lltm_cuda_kernem.cu file. Be aware that it might trigger compilation errors with gcc7.

See a solution with arg casting in aforementioned issue in case it happens
