### ISSUE TITLE
`None` Default Arguments

### ISSUE THREAD

**Issue by rusty1s** [pytorch/extension-cpp#5]
Hello and thanks for this great repository!

Can you give me a hint on how to implement default arguments? I tried the following so far but it does not work:

```
at::Tensor torch_func(at::Tensor tensor1, at::Tensor tensor2={}) {
  ...
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("torch_func", &torch_func, py::arg("tensor1"), py::arg("tensor2")={});
}
```

```python
torch_func(tensor1, None)
```

I would be very grateful for help.

- OS: macOS
- PyTorch version: 0.4.0
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.6
- CUDA/cuDNN version:  -
- GPU models and configuration: -
- GCC version (if compiling from source): 4.9

**Comment by goldsborough** [comment]
Hi, we don't currently provide a way of creating a "void"/"None" Tensor in our C++ extension API. Would it be enough for you to use something like `at::empty(torch::CPU(at::kDouble), {0}));` as the default argument and then check with `.numel() == 0` whether or not it is empty? This would work both in the function prototype and for the `py::arg()  = ...` .

Let me know whether this would be sufficient for you.

**Comment by rusty1s** [comment]
Thanks! `python setup.py install` now works perfectly.

However, calling the function in Python with a `None` argument gives the following error message:

```
incompatible function arguments. The following argument types are supported:
1. (tensor1: at::Tensor, tensor2 = tensor([], dtype=torch.float64)) -> at::Tensor

Invoked with: tensor([2, 2]), None
```

**Comment by rusty1s** [comment]
Yeah, I see. Actually, I wanted to pass `None`, but I guess I'm fine with the proposed solution (unless you know of an easy way to allow for `None` arguments). Thanks again!

**Comment by goldsborough** [comment]
I will keep the possibility of `None` converting to an undefined Tensor in mind as we expand the extension API. Thanks for posting the issue! I'll mark it as resolved.

**Comment by apaszke** [comment]
@goldsborough how about we expose `torch::optional` and let `None`s bind to that?

**Comment by goldsborough** [comment]
Yes that's a good idea, I'll do that

**Comment by goldsborough** [comment]
@rusty1s you can now pass `None` if you use `at::optional<at::Tensor>` in C++ (and `at::nullopt` or `nullptr` as the C++ default type)
