### ISSUE TITLE
python benchmark cpp has segmentation fault

### ISSUE THREAD

**Issue by renfeier** [pytorch/extension-cpp#52]
PyTorch GitHub Issues Guidelines
--------------------------------
- OS:  x86_64-redhat-linux
- PyTorch version: 1.3.1
- How you installed PyTorch (conda, pip, source): pip
- Python version:python3.6
- CUDA/cuDNN version:CUDA 10.0
- GPU models and configuration:
- GCC version (if compiling from source):
gcc 4.8.5
In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do
=====================

python benchmark.py cpp
Segmentation fault

**Comment by renfeier** [comment]
@ClementPinard

**Comment by ClementPinard** [comment]
Hi,

As seen [here] (https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py#L53), the minimum supported gcc version is gcc 4.9 and you use 4.8

I think (but I'm not sure) that this can be solved if you build pytorch from source with your gcc 4.8

Clément
