### ISSUE TITLE
Writing a custom C++ extension with variants for both CPU and GPU?

### ISSUE THREAD

**Issue by MalayAgr** [pytorch/extension-cpp#77]
Hi.

I am interested in writing a custom C++/CUDA extension.

The tutorial [here](https://pytorch.org/tutorials/advanced/cpp_extension.html) only shows a scenario where you have a pure CUDA kernel which will not work on a machine which doesn’t have CUDA. I’d like to make an extension which uses a CPU version OR the CUDA version automatically, akin to what PyTorch itself does. I was wondering if there was a way to use the dispatcher in PyTorch to accomplish this in the extension. I know this can be done using if statements or #if preprocessors. But I’d like a slightly more “automatic” solution.

Thank you!

P.S.: I have already searched the discussion forums for this topic but couldn’t find a solution.

**Comment by ClementPinard** [comment]
Hello, I implemented the CUDA/CPU flexibility myself in this project : https://github.com/ClementPinard/Pytorch-Correlation-extension

**Comment by MalayAgr** [comment]
Yeah, I ended up going the `if` route in the end.
